-- ROLLBACK for auth-broad-drop.sql — recreates the 55 policies verbatim (2026-05-16)
BEGIN;
CREATE POLICY "Auth full access clients" ON public.clients AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_clients" ON public.clients AS PERMISSIVE FOR DELETE TO authenticated USING (true);
CREATE POLICY "auth_read" ON public.clients AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_read_clients" ON public.clients AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_clients" ON public.clients AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "auth_write" ON public.clients AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write_clients" ON public.clients AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "service_write" ON public.competitors AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated read crew_locations" ON public.crew_locations AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users update own location" ON public.crew_locations AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Users upsert own location" ON public.crew_locations AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_read" ON public.crew_locations AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write" ON public.crew_locations AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth full access expenses" ON public.expenses AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth full access invoices" ON public.invoices AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_read" ON public.invoices AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_read_invoices" ON public.invoices AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_invoices" ON public.invoices AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "auth_write" ON public.invoices AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write_invoices" ON public.invoices AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth full access jobs" ON public.jobs AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_read" ON public.jobs AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_read_jobs" ON public.jobs AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_jobs" ON public.jobs AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "auth_write" ON public.jobs AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write_jobs" ON public.jobs AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "auth_full_marketing_drafts" ON public.marketing_drafts AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Auth full access payments" ON public.payments AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_read" ON public.payments AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write" ON public.payments AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "service_all" ON public.portal_sessions AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "Auth full access quotes" ON public.quotes AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_read" ON public.quotes AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_read_quotes" ON public.quotes AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_quotes" ON public.quotes AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "auth_write" ON public.quotes AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write_quotes" ON public.quotes AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth full access requests" ON public.requests AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_read" ON public.requests AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_read_requests" ON public.requests AS PERMISSIVE FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_requests" ON public.requests AS PERMISSIVE FOR UPDATE TO authenticated USING (true);
CREATE POLICY "auth_write" ON public.requests AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write_requests" ON public.requests AS PERMISSIVE FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Auth full access services" ON public.services AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_read" ON public.services AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write" ON public.services AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth full access team_members" ON public.team_members AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_all_team" ON public.team_members AS PERMISSIVE FOR ALL TO authenticated USING (true);
CREATE POLICY "auth_read" ON public.team_members AS PERMISSIVE FOR SELECT TO public USING ((auth.role() = 'authenticated'::text));
CREATE POLICY "auth_write" ON public.team_members AS PERMISSIVE FOR ALL TO public USING ((auth.role() = 'authenticated'::text)) WITH CHECK ((auth.role() = 'authenticated'::text));
CREATE POLICY "Auth full access time_entries" ON public.time_entries AS PERMISSIVE FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_all_time" ON public.time_entries AS PERMISSIVE FOR ALL TO authenticated USING (true);
CREATE POLICY "service_write_vmaint" ON public.vehicle_maintenance AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_write_vpos" ON public.vehicle_positions AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "service_write_vehicles" ON public.vehicles AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
COMMIT;
