-- 2026-05-17 corrective pass: (a) restore owner access to 8 tables whose only
-- policies were dropped by the breach fix, (b) close residual anon leaks on
-- tasks/chip_drop_spots (their *_tenant_* TO public hardcoded-SNT policies).
-- Correct white-label pattern: TO authenticated, tenant_id = current_tenant_id().
BEGIN;
DROP POLICY IF EXISTS "tasks_tenant_select" ON public.tasks;
DROP POLICY IF EXISTS "tasks_tenant_insert" ON public.tasks;
DROP POLICY IF EXISTS "tasks_tenant_update" ON public.tasks;
DROP POLICY IF EXISTS "tasks_tenant_delete" ON public.tasks;
DROP POLICY IF EXISTS "chip_drop_tenant_select" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "chip_drop_tenant_insert" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "chip_drop_tenant_update" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "chip_drop_tenant_delete" ON public.chip_drop_spots;
CREATE POLICY "tenant_auth_select_tasks" ON public.tasks FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_tasks" ON public.tasks FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_tasks" ON public.tasks FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_tasks" ON public.tasks FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_chip_drop_spots" ON public.chip_drop_spots FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_chip_drop_spots" ON public.chip_drop_spots FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_chip_drop_spots" ON public.chip_drop_spots FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_chip_drop_spots" ON public.chip_drop_spots FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_bank_accounts" ON public.bank_accounts FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_bank_accounts" ON public.bank_accounts FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_bank_accounts" ON public.bank_accounts FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_bank_accounts" ON public.bank_accounts FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_bank_transactions" ON public.bank_transactions FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_bank_transactions" ON public.bank_transactions FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_bank_transactions" ON public.bank_transactions FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_bank_transactions" ON public.bank_transactions FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_chart_of_accounts" ON public.chart_of_accounts FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_chart_of_accounts" ON public.chart_of_accounts FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_chart_of_accounts" ON public.chart_of_accounts FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_chart_of_accounts" ON public.chart_of_accounts FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_competitors" ON public.competitors FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_competitors" ON public.competitors FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_competitors" ON public.competitors FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_competitors" ON public.competitors FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_crew_locations" ON public.crew_locations FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_crew_locations" ON public.crew_locations FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_crew_locations" ON public.crew_locations FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_crew_locations" ON public.crew_locations FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_marketing_drafts" ON public.marketing_drafts FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_marketing_drafts" ON public.marketing_drafts FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_marketing_drafts" ON public.marketing_drafts FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_marketing_drafts" ON public.marketing_drafts FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_onboarding_signatures" ON public.onboarding_signatures FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_onboarding_signatures" ON public.onboarding_signatures FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_onboarding_signatures" ON public.onboarding_signatures FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_onboarding_signatures" ON public.onboarding_signatures FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_select_portal_sessions" ON public.portal_sessions FOR SELECT TO authenticated USING (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_insert_portal_sessions" ON public.portal_sessions FOR INSERT TO authenticated WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_update_portal_sessions" ON public.portal_sessions FOR UPDATE TO authenticated USING (tenant_id = current_tenant_id()) WITH CHECK (tenant_id = current_tenant_id());
CREATE POLICY "tenant_auth_delete_portal_sessions" ON public.portal_sessions FOR DELETE TO authenticated USING (tenant_id = current_tenant_id());
COMMIT;
