-- rollback the 2026-05-17 corrective pass
BEGIN;
DROP POLICY IF EXISTS "tenant_auth_select_tasks" ON public.tasks;
DROP POLICY IF EXISTS "tenant_auth_insert_tasks" ON public.tasks;
DROP POLICY IF EXISTS "tenant_auth_update_tasks" ON public.tasks;
DROP POLICY IF EXISTS "tenant_auth_delete_tasks" ON public.tasks;
DROP POLICY IF EXISTS "tenant_auth_select_chip_drop_spots" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "tenant_auth_insert_chip_drop_spots" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "tenant_auth_update_chip_drop_spots" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "tenant_auth_delete_chip_drop_spots" ON public.chip_drop_spots;
DROP POLICY IF EXISTS "tenant_auth_select_bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "tenant_auth_insert_bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "tenant_auth_update_bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "tenant_auth_delete_bank_accounts" ON public.bank_accounts;
DROP POLICY IF EXISTS "tenant_auth_select_bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "tenant_auth_insert_bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "tenant_auth_update_bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "tenant_auth_delete_bank_transactions" ON public.bank_transactions;
DROP POLICY IF EXISTS "tenant_auth_select_chart_of_accounts" ON public.chart_of_accounts;
DROP POLICY IF EXISTS "tenant_auth_insert_chart_of_accounts" ON public.chart_of_accounts;
DROP POLICY IF EXISTS "tenant_auth_update_chart_of_accounts" ON public.chart_of_accounts;
DROP POLICY IF EXISTS "tenant_auth_delete_chart_of_accounts" ON public.chart_of_accounts;
DROP POLICY IF EXISTS "tenant_auth_select_competitors" ON public.competitors;
DROP POLICY IF EXISTS "tenant_auth_insert_competitors" ON public.competitors;
DROP POLICY IF EXISTS "tenant_auth_update_competitors" ON public.competitors;
DROP POLICY IF EXISTS "tenant_auth_delete_competitors" ON public.competitors;
DROP POLICY IF EXISTS "tenant_auth_select_crew_locations" ON public.crew_locations;
DROP POLICY IF EXISTS "tenant_auth_insert_crew_locations" ON public.crew_locations;
DROP POLICY IF EXISTS "tenant_auth_update_crew_locations" ON public.crew_locations;
DROP POLICY IF EXISTS "tenant_auth_delete_crew_locations" ON public.crew_locations;
DROP POLICY IF EXISTS "tenant_auth_select_marketing_drafts" ON public.marketing_drafts;
DROP POLICY IF EXISTS "tenant_auth_insert_marketing_drafts" ON public.marketing_drafts;
DROP POLICY IF EXISTS "tenant_auth_update_marketing_drafts" ON public.marketing_drafts;
DROP POLICY IF EXISTS "tenant_auth_delete_marketing_drafts" ON public.marketing_drafts;
DROP POLICY IF EXISTS "tenant_auth_select_onboarding_signatures" ON public.onboarding_signatures;
DROP POLICY IF EXISTS "tenant_auth_insert_onboarding_signatures" ON public.onboarding_signatures;
DROP POLICY IF EXISTS "tenant_auth_update_onboarding_signatures" ON public.onboarding_signatures;
DROP POLICY IF EXISTS "tenant_auth_delete_onboarding_signatures" ON public.onboarding_signatures;
DROP POLICY IF EXISTS "tenant_auth_select_portal_sessions" ON public.portal_sessions;
DROP POLICY IF EXISTS "tenant_auth_insert_portal_sessions" ON public.portal_sessions;
DROP POLICY IF EXISTS "tenant_auth_update_portal_sessions" ON public.portal_sessions;
DROP POLICY IF EXISTS "tenant_auth_delete_portal_sessions" ON public.portal_sessions;
CREATE POLICY "chip_drop_tenant_select" ON public.chip_drop_spots AS PERMISSIVE FOR SELECT TO public USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "chip_drop_tenant_insert" ON public.chip_drop_spots AS PERMISSIVE FOR INSERT TO public WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "chip_drop_tenant_update" ON public.chip_drop_spots AS PERMISSIVE FOR UPDATE TO public USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "chip_drop_tenant_delete" ON public.chip_drop_spots AS PERMISSIVE FOR DELETE TO public USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "tasks_tenant_select" ON public.tasks AS PERMISSIVE FOR SELECT TO public USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "tasks_tenant_insert" ON public.tasks AS PERMISSIVE FOR INSERT TO public WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "tasks_tenant_update" ON public.tasks AS PERMISSIVE FOR UPDATE TO public USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "tasks_tenant_delete" ON public.tasks AS PERMISSIVE FOR DELETE TO public USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
COMMIT;
