-- BM LOCKDOWN ROLLBACK (generated 2026-05-15) — recreates the exact 210
-- policies verbatim from pre-change metadata. EMERGENCY USE: restores the
-- vulnerable-but-working state if BM breaks post-lockdown.
BEGIN;
CREATE POLICY "mt_anon_delete" ON public.chip_drop_spots AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.chip_drop_spots AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.chip_drop_spots AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.chip_drop_spots AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.chip_drop_spots AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.chip_drop_spots AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.chip_drop_spots AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.chip_drop_spots AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.clients AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.clients AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.clients AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.clients AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.clients AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.clients AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.clients AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.clients AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.communications AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.communications AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.communications AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.communications AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.communications AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.communications AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.communications AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.communications AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.competitors AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.competitors AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.competitors AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.competitors AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.competitors AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.competitors AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.competitors AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.competitors AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.crew_locations AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.crew_locations AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.crew_locations AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.crew_locations AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.crew_locations AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.crew_locations AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.crew_locations AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.crew_locations AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.detected_locations AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.detected_locations AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.detected_locations AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.detected_locations AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.detected_locations AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.detected_locations AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.detected_locations AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.detected_locations AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.expenses AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.expenses AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.expenses AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.expenses AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.expenses AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.expenses AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.expenses AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.expenses AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.invoices AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.invoices AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.invoices AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.invoices AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.invoices AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.invoices AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.invoices AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.invoices AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.jobs AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.jobs AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.jobs AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.jobs AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.jobs AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.jobs AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.jobs AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.jobs AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.location_pings AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.location_pings AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.location_pings AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.location_pings AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.location_pings AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.location_pings AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.location_pings AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.location_pings AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.materials AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.materials AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.materials AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.materials AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.materials AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.materials AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.materials AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.materials AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.onboarding_signatures AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.onboarding_signatures AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.payments AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.payments AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.payments AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.payments AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.payments AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.payments AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.payments AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.payments AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.photos AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.photos AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.photos AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.photos AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.photos AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.photos AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.photos AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.photos AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.portal_sessions AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.portal_sessions AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.portal_sessions AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.portal_sessions AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.portal_sessions AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.portal_sessions AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.portal_sessions AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.portal_sessions AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.quotes AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.quotes AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.quotes AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.quotes AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.quotes AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.quotes AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.quotes AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.quotes AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.recurring AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.recurring AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.recurring AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.recurring AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.recurring AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.recurring AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.recurring AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.recurring AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.requests AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.requests AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.requests AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.requests AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.requests AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.requests AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.requests AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.requests AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.services AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.services AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.services AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.services AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.services AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.services AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.services AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.services AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.tasks AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.tasks AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.tasks AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.tasks AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.tasks AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.tasks AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.tasks AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.tasks AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.team_members AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.team_members AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.team_members AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.team_members AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.team_members AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.team_members AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.team_members AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.team_members AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.team_messages AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.team_messages AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.team_messages AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.team_messages AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.team_messages AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.team_messages AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.team_messages AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.team_messages AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.time_entries AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.time_entries AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.time_entries AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.time_entries AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.time_entries AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.time_entries AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.time_entries AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.time_entries AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.vehicle_maintenance AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.vehicle_maintenance AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.vehicle_maintenance AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.vehicle_maintenance AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.vehicle_maintenance AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.vehicle_maintenance AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.vehicle_maintenance AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.vehicle_maintenance AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.vehicle_positions AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.vehicle_positions AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.vehicle_positions AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.vehicle_positions AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.vehicle_positions AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.vehicle_positions AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.vehicle_positions AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.vehicle_positions AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.vehicles AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.vehicles AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.vehicles AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.vehicles AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.vehicles AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.vehicles AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.vehicles AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.vehicles AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "mt_anon_delete" ON public.visits AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_insert" ON public.visits AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_select" ON public.visits AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = current_tenant_id()));
CREATE POLICY "mt_anon_update" ON public.visits AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "snt_anon_delete" ON public.visits AS PERMISSIVE FOR DELETE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_insert" ON public.visits AS PERMISSIVE FOR INSERT TO anon WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_select" ON public.visits AS PERMISSIVE FOR SELECT TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
CREATE POLICY "snt_anon_update" ON public.visits AS PERMISSIVE FOR UPDATE TO anon USING ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid)) WITH CHECK ((tenant_id = '93af4348-8bba-4045-ac3e-5e71ec1cc8c5'::uuid));
COMMIT;
