BEGIN;
DROP POLICY IF EXISTS "tenant_isolation_clients" ON public.clients;
DROP POLICY IF EXISTS "tenant_isolation_communications" ON public.communications;
DROP POLICY IF EXISTS "tenant_isolation_select" ON public.compliance_documents;
DROP POLICY IF EXISTS "tenant_isolation_write" ON public.compliance_documents;
DROP POLICY IF EXISTS "tenant_isolation_select" ON public.expenses;
DROP POLICY IF EXISTS "tenant_isolation_expenses" ON public.expenses;
DROP POLICY IF EXISTS "tenant_isolation_write" ON public.expenses;
DROP POLICY IF EXISTS "tenant_isolation_invoices" ON public.invoices;
DROP POLICY IF EXISTS "tenant_isolation_jobs" ON public.jobs;
DROP POLICY IF EXISTS "tenant_isolation_materials" ON public.materials;
DROP POLICY IF EXISTS "tenant_isolation_write" ON public.onboarding_uploads;
DROP POLICY IF EXISTS "tenant_isolation_select" ON public.onboarding_uploads;
DROP POLICY IF EXISTS "tenant_isolation_payments" ON public.payments;
DROP POLICY IF EXISTS "tenant_isolation_photos" ON public.photos;
DROP POLICY IF EXISTS "tenant_isolation_quotes" ON public.quotes;
DROP POLICY IF EXISTS "tenant_isolation_recurring" ON public.recurring;
DROP POLICY IF EXISTS "tenant_isolation_requests" ON public.requests;
DROP POLICY IF EXISTS "tenant_isolation_services" ON public.services;
DROP POLICY IF EXISTS "tenant_isolation_team_members" ON public.team_members;
DROP POLICY IF EXISTS "tenant_isolation_write" ON public.time_entries;
DROP POLICY IF EXISTS "tenant_isolation_select" ON public.time_entries;
DROP POLICY IF EXISTS "tenant_isolation_time_entries" ON public.time_entries;
DROP POLICY IF EXISTS "tenant_isolation_visits" ON public.visits;
CREATE POLICY "tenant_isolation_clients" ON public.clients AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_communications" ON public.communications AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_select" ON public.compliance_documents AS PERMISSIVE FOR SELECT TO public USING ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_write" ON public.compliance_documents AS PERMISSIVE FOR ALL TO public USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_select" ON public.expenses AS PERMISSIVE FOR SELECT TO public USING ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_expenses" ON public.expenses AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_write" ON public.expenses AS PERMISSIVE FOR ALL TO public USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_invoices" ON public.invoices AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_jobs" ON public.jobs AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_materials" ON public.materials AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_write" ON public.onboarding_uploads AS PERMISSIVE FOR ALL TO public USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_select" ON public.onboarding_uploads AS PERMISSIVE FOR SELECT TO public USING ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_payments" ON public.payments AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_photos" ON public.photos AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_quotes" ON public.quotes AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_recurring" ON public.recurring AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_requests" ON public.requests AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_services" ON public.services AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_team_members" ON public.team_members AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_write" ON public.time_entries AS PERMISSIVE FOR ALL TO public USING ((tenant_id = current_tenant_id())) WITH CHECK ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_select" ON public.time_entries AS PERMISSIVE FOR SELECT TO public USING ((tenant_id = current_tenant_id()));
CREATE POLICY "tenant_isolation_time_entries" ON public.time_entries AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
CREATE POLICY "tenant_isolation_visits" ON public.visits AS PERMISSIVE FOR ALL TO authenticated USING (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL))) WITH CHECK (((tenant_id = current_tenant_id()) OR (current_tenant_id() IS NULL)));
COMMIT;
